import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import TanstackQueryProvider from '@/components/queryProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <TanstackQueryProvider>
        <body className={inter.className}>{children}</body>
      </TanstackQueryProvider>
    </html>
  )
}
